### PR TITLE
Adds banner into primo when not logged in

### LINKED ISSUE #4: Add message to header: Not finding what you need - sign in!
When a user is not signed in, display the message "Not finding what you need? - Sign in" that links to login.

Example from WWU:
 http://alliance-primo.hosted.exlibrisgroup.com/primo_library/libweb/action/dlSearch.do?institution=WALLA&vid=WALLA&onCampus=true&group=GUEST&highlight=true&displayMode=full&displayField=all&query=any%2Ccontains%2Cstuff&queryTemp=stuff&search_scope=walla_alma_summit&tab=default_tab&pcAvailabilityMode=true&mode=Basic&indx=1&bulkSize=20

### PR DESCRIPTION
**Pull request by straleyb**
So there were some odd things when creating the appended_string. When trying to end the html divs </strong></div> having the / in there was making my vim throw some warnings. Im pretty sure it should be fine, but I just wanted to let you know. Fixes #4.

### CODE REVIEW

**Comment by mickeroo** [comment]
For $('#exlidSignOut').hasClass('EXLHidden') to have a valid value when it runs, we need to wrap the whole function in $(document).ready.

Also, I was thinking that we could grab the login link from the "Sign In" link in the upper right.  Since Primo generated this for us already AND it's got the view ID and search term cached, if we use this href then we get to keep what we were searching for and we don't have to custom code the URL for each version.  Something like this:

```
var signInLink = $('li#exlidSignIn a').attr('href');
```

**Comment by straleyb** [comment]
:+1: Cool. I can get those changed and pushed back up.

**Comment by straleyb** [comment]
@mickeroo should be changed now.

**Comment by mickeroo** [comment]
One last thing: Victoria has a verbiage change for the message:

You are not signed in. Sign in for additional full-text and delivery/request options.

...with "Sign in" being the link using signInLink above

**Pull request merged**
